### ISSUE TITLE
Full Scannet++ Dataset?

### ISSUE THREAD

**Issue by trandangtrungduc** [RayYoh/SGIFormer#2]
Thanks for your interesting work.

As far as I know at [here](https://github.com/scannetpp/scannetpp/issues/91), Scannet++ has only released 230/50/50 scans corresponding to 3 sets of train/val/test. How can you use all 360 scans or do you only train on 230 scans?

**Comment by RayYoh** [comment]
Hi, thanks for your question. Actually, I have checked the split file of ScanNet++, and it only has 230 training scans, 50 validating scans, and 50 testing scans. But when we wrote the paper, we referred to the original paper of ScanNet++ ([Section 3.6](https://arxiv.org/pdf/2308.11417)). Because now it uses the latest version which is different from their paper.

For training, we just use 230 scans. For submitting, we use 230+50 scans, which is a common technique for ScanNetV2.

We will revise our paper to make it correct.
